version: "3.8"

services:
    lambda-php:
        image: bref/php-82-fpm-dev:2
        ports:
            - "8000:8000"
        volumes:
            - .:/var/task
            - ./wordlist.txt:/var/task/wordlist.txt
            - ./custom.ini:/opt/bref/etc/php/conf.d/custom.ini
        environment:
            BREF_PHP_DISPLAY_ERRORS: 1
            HANDLER: src/index.php
            # LAMBDA_TASK_ROOT: /var/task
            # DB_DSN: "mysql:localhost=db;dbname=lambda;charset=utf8mb4"
            DB_USER: lambda
            DB_PASS: password
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: mysql_server
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: lambda
            MYSQL_USER: lambda
            MYSQL_PASSWORD: password
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
